server.port=8081

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/microfinancehub_client}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:axelle3928}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway desactive
spring.flyway.enabled=false

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Même noms que auth-service (publisher/consumer du même event)
rabbitmq.queue.user-login=user.login.queue
rabbitmq.exchange.user-events=user.events.exchange
rabbitmq.routing-key.user-login=user.login

# Auth Service URL
auth.service.url=http://localhost:8080

# Redis (pour le rate limiting)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# Management
management.endpoints.web.exposure.include=health,info,metrics

# Logging
logging.level.org.example.clientservice=DEBUG
logging.level.org.springframework.security=INFO
