server.port=8087

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/microfinancehub_configuration}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway desactive
spring.flyway.enabled=false

# JWT
jwt.secret=${JWT_SECRET}

# Management
management.endpoints.web.exposure.include=health,info,metrics

# Logging
logging.level.org.example.configurationservice=DEBUG
logging.level.org.springframework.security=INFO
