server.port=8087

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/microfinancehub_configuration}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:axelle3928}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway desactive
spring.flyway.enabled=false

# JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# Management
management.endpoints.web.exposure.include=health,info,metrics

# Logging
logging.level.org.example.configurationservice=DEBUG
logging.level.org.springframework.security=INFO
