server.port=8083

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/microfinancehub_loan}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:axelle3928}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway desactive (pas encore de scripts de migration)
spring.flyway.enabled=false

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Auth Service URL
auth.service.url=http://localhost:8080

# JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# Token interne
internal.api.token=${INTERNAL_API_TOKEN:my-super-secret-internal-token-2026}

# Feign timeouts
spring.cloud.openfeign.client.config.default.connect-timeout=10000
spring.cloud.openfeign.client.config.default.read-timeout=10000

# Management
management.endpoints.web.exposure.include=health,info,metrics

# Logging
logging.level.org.example.loanservice=DEBUG
logging.level.org.springframework.security=INFO
