server.port=8085

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/microfinancehub_reporting}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway desactive
spring.flyway.enabled=false

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Service URLs
loan.service.url=http://loan-service:8083
repayment.service.url=http://repayment-service:8084
client.service.url=http://client-service:8081

# JWT
jwt.secret=${JWT_SECRET}

# Management
management.endpoints.web.exposure.include=health,info,metrics

# Logging
logging.level.org.example.reportingservice=DEBUG
logging.level.org.springframework.security=INFO
