server.port=8088

spring.datasource.url= ${DB_URL:jdbc:postgresql://localhost:5433/microfinancehub_transaction}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:axelle3928}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.data.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.data.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.data.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.data.rabbitmq.virtual-host=/

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

app.rabbitmq.exchange=finance.exchange
app.rabbitmq.routingkey=balance.updated
app.transaction.montant-minimum=1

# URL interne du service-compte (sans gateway pour l'instant)
account.service.url=${ACCOUNT_SERVICE_URL:http://localhost:8083}


# Configuration JWT (partagée avec tous les services)
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000    # 24h en millisecondes


# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always


# Logging
logging.level.com.microfinancehub=DEBUG
logging.level.org.springframework.security=INFO
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# CamPay
campay.base.url=${CAMPAY_BASE_URL:https://demo.campay.net/api}

campay.app.username=${CAMPAY_USERNAME:REMPLACER_PAR_TON_USERNAME}
campay.app.password=${CAMPAY_PASSWORD:REMPLACER_PAR_TON_PASSWORD}
campay.app.webhook.key=${CAMPAY_WEBHOOK_KEY:REMPLACER_PAR_TON_WEBHOOK_KEY}
campay.app.permanent-access-token=${CAMPAY_PERMANENT_TOKEN:REMPLACER_PAR_TON_TOKEN_PROD}
