server.port=8088

spring.datasource.url= ${DB_URL:jdbc:postgresql://postgres:5432/microfinancehub_transaction}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=/

eureka.client.service-url.defaultZone=${EUREKA_URL:http://registry-service:8761/eureka/}

app.rabbitmq.exchange=finance.exchange
app.rabbitmq.routingkey=balance.updated
app.transaction.montant-minimum=1

# URL interne du service-compte (sans gateway pour l'instant)
account.service.url=${ACCOUNT_SERVICE_URL:http://account-service:8082}


# Configuration JWT (partagée avec tous les services)
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always


# Logging
logging.level.com.microfinancehub=DEBUG
logging.level.org.springframework.security=INFO
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# CamPay
campay.base.url=${CAMPAY_BASE_URL}

campay.app.username=${CAMPAY_USERNAME}
campay.app.password=${CAMPAY_PASSWORD}
campay.app.webhook.key=${CAMPAY_WEBHOOK_KEY}
campay.app.permanent-access-token=${CAMPAY_PERMANENT_TOKEN}
